// 文件类型图标（vscode-icons 风格）。图标本体 = vendored Material Icon Theme
// v5.38.1 SVG（MIT，assets/fileicons/LICENSE），下表按其官方清单
// dist/material-icons.json 摘编——不要手改映射，缺类型就补 SVG + 补表。
// 未命中的扩展名落通用 'file'，未识别的目录名落 'folder'/'folder-open'。

export type TreeKind = 'file' | 'dir' | 'link'

const EXT_ICONS: Record<string, string> = {
  '7z': 'zip',
  'adoc': 'asciidoc',
  'astro': 'astro',
  'avi': 'video',
  'avif': 'image',
  'awk': 'console',
  'bash': 'console',
  'bat': 'console',
  'bib': 'bibliography',
  'bmp': 'image',
  'bz2': 'zip',
  'c': 'c',
  'cc': 'cpp',
  'cer': 'certificate',
  'cfg': 'settings',
  'cjs': 'javascript',
  'class': 'javaclass',
  'clj': 'clojure',
  'cljc': 'clojure',
  'cljs': 'clojure',
  'cmd': 'console',
  'conf': 'settings',
  'cpp': 'cpp',
  'cr': 'crystal',
  'crt': 'certificate',
  'cs': 'csharp',
  'css': 'css',
  'csv': 'table',
  'cts': 'typescript',
  'cxx': 'cpp',
  'd': 'd',
  'dart': 'dart',
  'db': 'database',
  'diff': 'diff',
  'dll': 'dll',
  'dmg': 'disc',
  'dockerignore': 'docker',
  'drawio': 'drawio',
  'edn': 'clojure',
  'ejs': 'ejs',
  'env': 'tune',
  'eot': 'font',
  'epub': 'epub',
  'erb': 'ruby',
  'erl': 'erlang',
  'ex': 'elixir',
  'exe': 'exe',
  'exs': 'elixir',
  'fish': 'console',
  'flac': 'audio',
  'fs': 'fsharp',
  'fsx': 'fsharp',
  'gif': 'image',
  'go': 'go',
  'gql': 'graphql',
  'gradle': 'gradle',
  'graphql': 'graphql',
  'groovy': 'groovy',
  'gz': 'zip',
  'h': 'h',
  'handlebars': 'handlebars',
  'hbs': 'handlebars',
  'hcl': 'hcl',
  'hh': 'hpp',
  'hpp': 'hpp',
  'hs': 'haskell',
  'htm': 'html',
  'html': 'html',
  'ico': 'image',
  'ini': 'settings',
  'ipynb': 'jupyter',
  'iso': 'disc',
  'jar': 'jar',
  'java': 'java',
  'jinja': 'jinja',
  'jinja2': 'jinja',
  'jl': 'julia',
  'jpeg': 'image',
  'jpg': 'image',
  'js': 'javascript',
  'json': 'json',
  'json5': 'json',
  'jsonc': 'json',
  'jsonl': 'json',
  'jsx': 'react',
  'key': 'key',
  'kt': 'kotlin',
  'kts': 'kotlin',
  'less': 'less',
  'lhs': 'haskell',
  'liquid': 'liquid',
  'lock': 'lock',
  'log': 'log',
  'lua': 'lua',
  'm4a': 'audio',
  'markdown': 'markdown',
  'md': 'markdown',
  'mdx': 'mdx',
  'mjs': 'javascript',
  'mkv': 'video',
  'ml': 'ocaml',
  'mli': 'ocaml',
  'mov': 'video',
  'mp3': 'audio',
  'mp4': 'video',
  'mts': 'typescript',
  'nim': 'nim',
  'nix': 'nix',
  'njk': 'nunjucks',
  'ogg': 'video',
  'otf': 'font',
  'patch': 'git',
  'pdf': 'pdf',
  'pem': 'key',
  'php': 'php',
  'plist': 'xml',
  'png': 'image',
  'properties': 'settings',
  'proto': 'proto',
  'ps1': 'powershell',
  'psm1': 'powershell',
  'pub': 'key',
  'py': 'python',
  'pyi': 'python',
  'r': 'r',
  'rar': 'zip',
  'rb': 'ruby',
  'rs': 'rust',
  'rst': 'markdown',
  'sass': 'sass',
  'scala': 'scala',
  'scss': 'sass',
  'sh': 'console',
  'so': 'dll',
  'sol': 'solidity',
  'sql': 'database',
  'sqlite': 'database',
  'sqlite3': 'database',
  'styl': 'stylus',
  'svelte': 'svelte',
  'svg': 'svg',
  'swift': 'swift',
  'tar': 'zip',
  'tex': 'tex',
  'tf': 'terraform',
  'tfvars': 'terraform',
  'tiff': 'image',
  'toml': 'toml',
  'ts': 'typescript',
  'tsv': 'table',
  'tsx': 'react_ts',
  'ttf': 'font',
  'twig': 'twig',
  'txt': 'document',
  'typ': 'typst',
  'vb': 'visualstudio',
  'vue': 'vue',
  'wasm': 'webassembly',
  'wav': 'audio',
  'webm': 'video',
  'webp': 'image',
  'woff': 'font',
  'woff2': 'font',
  'xhtml': 'html',
  'xml': 'xml',
  'xsl': 'xml',
  'xz': 'zip',
  'yaml': 'yaml',
  'yml': 'yaml',
  'zig': 'zig',
  'zip': 'zip',
  'zsh': 'console',
}

// 复合后缀（按最末两段试配，如 foo.spec.ts → 'spec.ts'）。
const COMPOUND_EXT_ICONS: Record<string, string> = {
  'd.ts': 'typescript-def',
  'd.mts': 'typescript-def',
  'd.cts': 'typescript-def',
  'spec.ts': 'test-ts',
  'test.ts': 'test-ts',
  'cy.ts': 'test-ts',
  'spec.tsx': 'test-jsx',
  'test.tsx': 'test-jsx',
  'spec.js': 'test-js',
  'test.js': 'test-js',
  'stories.ts': 'storybook',
  'stories.tsx': 'storybook',
  'stories.jsx': 'storybook',
}

const NAME_ICONS: Record<string, string> = {
  '.babelrc': 'babel',
  '.editorconfig': 'editorconfig',
  '.env.development': 'tune',
  '.env.development.local': 'tune',
  '.env.example': 'tune',
  '.env.local': 'tune',
  '.env.production': 'tune',
  '.env.test': 'tune',
  '.eslintrc': 'eslint',
  '.eslintrc.js': 'eslint',
  '.eslintrc.json': 'eslint',
  '.gitattributes': 'git',
  '.gitignore': 'git',
  '.gitmodules': 'git',
  '.npmrc': 'npm',
  '.nvmrc': 'nodejs',
  '.prettierrc': 'prettier',
  '.prettierrc.json': 'prettier',
  '.prettierrc.yml': 'prettier',
  '.taurignore': 'tauri',
  '.travis.yml': 'travis',
  'agents.md': 'agent',
  'angular.json': 'angular',
  'astro.config.mjs': 'astro-config',
  'authors': 'authors',
  'azure-pipelines.yml': 'azure-pipelines',
  'babel.config.js': 'babel',
  'bun.lock': 'bun',
  'bun.lockb': 'bun',
  'cabal.project': 'cabal',
  'changelog.md': 'changelog',
  'cmakelists.txt': 'cmake',
  'codecov.yml': 'codecov',
  'codeowners': 'codeowners',
  'compose.yaml': 'docker',
  'compose.yml': 'docker',
  'containerfile': 'docker',
  'contributing.md': 'contributing',
  'contributors': 'authors',
  'copying': 'license',
  'deno.json': 'deno',
  'deno.jsonc': 'deno',
  'docker-compose.yaml': 'docker',
  'docker-compose.yml': 'docker',
  'dockerfile': 'docker',
  'esbuild.config.js': 'esbuild',
  'eslint.config.js': 'eslint',
  'eslint.config.mjs': 'eslint',
  'gemfile': 'gemfile',
  'go.mod': 'go-mod',
  'go.sum': 'go-mod',
  'gradle.properties': 'gradle',
  'gradlew': 'gradle',
  'jenkinsfile': 'jenkins',
  'jest.config.js': 'jest',
  'jest.config.ts': 'jest',
  'jsconfig.json': 'jsconfig',
  'license': 'license',
  'license.md': 'license',
  'license.txt': 'license',
  'makefile': 'makefile',
  'netlify.toml': 'netlify',
  'next.config.js': 'next',
  'next.config.mjs': 'next',
  'next.config.ts': 'next',
  'nuxt.config.ts': 'nuxt',
  'package-lock.json': 'nodejs',
  'package.json': 'nodejs',
  'pipfile': 'python-misc',
  'playwright.config.ts': 'playwright',
  'pnpm-lock.yaml': 'pnpm',
  'pnpm-workspace.yaml': 'pnpm',
  'poetry.lock': 'poetry',
  'pom.xml': 'maven',
  'postcss.config.js': 'postcss',
  'postcss.config.mjs': 'postcss',
  'prettier.config.js': 'prettier',
  'prettier.config.mjs': 'prettier',
  'pyproject.toml': 'python-misc',
  'readme': 'readme',
  'readme.md': 'readme',
  'renovate.json': 'renovate',
  'requirements.txt': 'python-misc',
  'rollup.config.js': 'rollup',
  'rollup.config.mjs': 'rollup',
  'svelte.config.js': 'svelte',
  'tailwind.config.js': 'tailwindcss',
  'tailwind.config.mjs': 'tailwindcss',
  'tailwind.config.ts': 'tailwindcss',
  'tauri.conf.json': 'tauri',
  'tsconfig.app.json': 'tsconfig',
  'tsconfig.build.json': 'tsconfig',
  'tsconfig.json': 'tsconfig',
  'tsconfig.node.json': 'tsconfig',
  'uv.lock': 'uv',
  'vercel.json': 'vercel',
  'vite.config.js': 'vite',
  'vite.config.ts': 'vite',
  'vitest.config.js': 'vitest',
  'vitest.config.ts': 'vitest',
  'webpack.config.js': 'webpack',
  'wrangler.toml': 'wrangler',
  'yarn.lock': 'yarn',
}

// 目录名 → [收起, 展开] 图标对。
const FOLDER_ICONS: Record<string, [string, string]> = {
  '.agents': ['folder-robot', 'folder-robot-open'],
  '.git': ['folder-git', 'folder-git-open'],
  '.github': ['folder-github', 'folder-github-open'],
  '.idea': ['folder-intellij', 'folder-intellij-open'],
  '.next': ['folder-next', 'folder-next-open'],
  '.vscode': ['folder-vscode', 'folder-vscode-open'],
  '__tests__': ['folder-test', 'folder-test-open'],
  'agent': ['folder-robot', 'folder-robot-open'],
  'agents': ['folder-robot', 'folder-robot-open'],
  'api': ['folder-api', 'folder-api-open'],
  'assets': ['folder-resource', 'folder-resource-open'],
  'bin': ['folder-dist', 'folder-dist-open'],
  'build': ['folder-dist', 'folder-dist-open'],
  'components': ['folder-components', 'folder-components-open'],
  'config': ['folder-config', 'folder-config-open'],
  'coverage': ['folder-coverage', 'folder-coverage-open'],
  'crates': ['folder-lib', 'folder-lib-open'],
  'css': ['folder-css', 'folder-css-open'],
  'dist': ['folder-dist', 'folder-dist-open'],
  'doc': ['folder-docs', 'folder-docs-open'],
  'docs': ['folder-docs', 'folder-docs-open'],
  'e2e': ['folder-coverage', 'folder-coverage-open'],
  'fonts': ['folder-font', 'folder-font-open'],
  'gen': ['folder-generator', 'folder-generator-open'],
  'i18n': ['folder-i18n', 'folder-i18n-open'],
  'icons': ['folder-images', 'folder-images-open'],
  'images': ['folder-images', 'folder-images-open'],
  'img': ['folder-images', 'folder-images-open'],
  'lib': ['folder-lib', 'folder-lib-open'],
  'locales': ['folder-i18n', 'folder-i18n-open'],
  'node_modules': ['folder-node', 'folder-node-open'],
  'out': ['folder-dist', 'folder-dist-open'],
  'public': ['folder-public', 'folder-public-open'],
  'resources': ['folder-resource', 'folder-resource-open'],
  'scripts': ['folder-scripts', 'folder-scripts-open'],
  'skills': ['folder-skills', 'folder-skills-open'],
  'spec': ['folder-test', 'folder-test-open'],
  'src': ['folder-src', 'folder-src-open'],
  'src-tauri': ['folder-src-tauri', 'folder-src-tauri-open'],
  'styles': ['folder-css', 'folder-css-open'],
  'target': ['folder-target', 'folder-target-open'],
  'test': ['folder-test', 'folder-test-open'],
  'tests': ['folder-test', 'folder-test-open'],
  'ui': ['folder-ui', 'folder-ui-open'],
}

/**
 * 条目 → 图标资产名（assets/fileicons/<name>.svg）。
 * dir 按 open 态取开/合形；link 无对应主题资产，调用方回退描边 Icon。
 */
export function fileIconAsset(name: string, kind: TreeKind, open = false): string {
  if (kind === 'dir') {
    const hit = FOLDER_ICONS[name.toLowerCase()]
    return hit ? hit[open ? 1 : 0] : open ? 'folder-open' : 'folder'
  }
  const base = name.toLowerCase()
  const byName = NAME_ICONS[base]
  if (byName) return byName
  const firstDot = base.indexOf('.')
  if (firstDot < 0) return 'file'
  const compound = COMPOUND_EXT_ICONS[base.slice(firstDot + 1)]
  if (compound) return compound
  return EXT_ICONS[base.slice(base.lastIndexOf('.') + 1)] ?? 'file'
}
